### ISSUE TITLE
Receiving '6' error code, causing KeyError

### ISSUE THREAD

**Issue by ZAD-Man** [hanneshapke/pyzillow#9]
This may very well be due to Zillow making changes without updating their docs or something, but I'm currently getting a '6' error code back when trying to use `get_deep_search_results()`, which is not a valid error code, so I get a `KeyError` when the `ZillowError` that should deal with the error code/message is raised. Here's the code I'm running, pretty simple:

```
from pyzillow.pyzillow import ZillowWrapper, GetDeepSearchResults

zillow_wrap = ZillowWrapper("[my key]")
search_res = zillow_wrap.get_deep_search_results("[my address]", "84084")
print GetDeepSearchResults(search_res).zillow_id
```

Any known reason this might be happening? The Zillow docs still align with the dict used to get the right message for the `ZillowError`, but I'll be contacting them next if needed.

**Comment by ZAD-Man** [comment]
Here's this if it helps:
```
Traceback (most recent call last):
  File "C:/Users/zad/Workspaces/PyzillowDemo/pyzillowTest.py", line 4, in <module>
    search_res = zillow_wrap.get_deep_search_results("[my address]", "84084")
  File "C:\Users\zad\Workspaces\ZillowEnv\lib\site-packages\pyzillow\pyzillow.py", line 31, in get_deep_search_results
    return self.get_data(url, params)
  File "C:\Users\zad\Workspaces\ZillowEnv\lib\site-packages\pyzillow\pyzillow.py", line 82, in get_data
    raise ZillowError(int(response.findall('message/code')[0].text))
  File "C:\Users\zad\Workspaces\ZillowEnv\lib\site-packages\pyzillow\pyzillowerrors.py", line 66, in __init__
    'text': self.code[int(status)]}
KeyError: 6
```

Also, visiting http://www.zillow.com/webservice/GetSearchResults.htm?zws-id=[mykey]&address=[myaddress]&citystatezip=84084 returns the data I expect, with a 0 status code.

**Comment by ZAD-Man** [comment]
Whoops, went to the wrong url. Going to the GetDeepSearchResults service instead got me this:
```
<message>
    <text>
        Error: this account is not authorized to execute this API call
    </text>
    <code>6</code>
</message>
```

So there you have it. Maybe that's documented somewhere and I missed it, but if anyone comes across this in the future, 6 means that you forgot to select the proper API, and therefore you aren't authorized! :)

**Comment by marcoacm** [comment]
Where did you find that was the right API call (GetDeepSearchResults). I can't find much documentation for the API. Can you send me a link for it?

**Comment by ZAD-Man** [comment]
Wow, someone really *did* see it in the future! :-D I don't remember much about this, but I'd be happy to poke around a bit and see what I can remember later today :-)

**Comment by marcoacm** [comment]
lol, I am writing from the year 2016!

**Comment by colot-imposter** [comment]
its one year later.... did you find the answer? @marcoacm
